In [46]:
import pandas as pd

In [47]:
url = "https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Bank%20Churn%20Modelling.csv"
df = pd.read_csv(url)
additional_df = pd.read_csv("Bank_Churn_Modelling_extra_UPDATED_v2.csv")

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerId        10000 non-null  int64
 1   Surname           10000 non-null  object
 2   CreditScore       10000 non-null  int64
 3   Geography         10000 non-null  object
 4   Gender            10000 non-null  object
 5   Age               10000 non-null  int64
 6   Tenure            10000 non-null  int64
 7   Balance           10000 non-null  float64
 8   Num Of Products   10000 non-null  int64
 9   Has Credit Card   10000 non-null  int64
 10  Is Active Member  10000 non-null  int64
 11  Estimated Salary  10000 non-null  float64
 12  Churn             10000 non-null  int64
dtypes: float64(2), int64(8), object(3)
memory usage: 1015.8+ KB

In [49]:
additional_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerId        49 non-null     int64
 1   Surname           49 non-null     object
 2   CreditScore       47 non-null     float64
 3   Geography         47 non-null     object
 4   Gender            48 non-null     object
 5   Age               46 non-null     float64
 6   Tenure            49 non-null     int64
 7   Balance           46 non-null     float64
 8   Num Of Products   49 non-null     int64
 9   Has Credit Card   49 non-null     int64
 10  Is Active Member  49 non-null     int64
 11  Estimated Salary  48 non-null     float64
 12  Churn             49 non-null     int64
dtypes: float64(4), int64(6), object(3)
memory usage: 5.1+ KB

In [50]:
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [51]:
additional_df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,Num Of Products,Has Credit Card,Is Active Member,Estimated Salary,Churn
0,15647819,Dlamini,536.0,Germany,Male,72.0,9,116534.69,4,1,1,163135.72,0
1,15587369,Jones,572.0,France,Female,NaN,4,153720.31,3,0,0,156006.35,0
2,15661951,VanNiekerk,357.0,Germany,Female,85.0,5,66304.03,2,0,0,166888.24,0
3,15567632,Jones,769.0,Spain,Male,NaN,2,33726.41,4,0,0,191141.68,1
4,15636646,Dlamini,378.0,Germany,NaN,62.0,9,0.00,1,1,0,197821.39,1

In [52]:
print("YBI Dataset Shape:", df.shape)
print("Additional Dataset Shape:", additional_df.shape)

YBI Dataset Shape: (10000, 13)
Additional Dataset Shape: (49, 13)

In [53]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'Num Of Products', 'Has Credit Card',
       'Is Active Member', 'Estimated Salary', 'Churn'],
      dtype='object')

In [54]:
additional_df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'Num Of Products', 'Has Credit Card',
       'Is Active Member', 'Estimated Salary', 'Churn'],
      dtype='object')

In [55]:
set(df.columns).intersection(set(additional_df.columns))

{'Age',
 'Balance',
 'Churn',
 'CreditScore',
 'CustomerId',
 'Estimated Salary',
 'Gender',
 'Geography',
 'Has Credit Card',
 'Is Active Member',
 'Num Of Products',
 'Surname',
 'Tenure'}

In [56]:
df.nunique()

CustomerId          10000
Surname              2932
CreditScore           460
Geography               3
Gender                  2
Age                    70
Tenure                 11
Balance              6382
Num Of Products         4
Has Credit Card         2
Is Active Member        2
Estimated Salary     9999
Churn                   2
dtype: int64

In [57]:
additional_df.nunique()

CustomerId          40
Surname             10
CreditScore         44
Geography            3
Gender               2
Age                 30
Tenure              10
Balance             43
Num Of Products      4
Has Credit Card      2
Is Active Member     2
Estimated Salary    45
Churn                2
dtype: int64

Format Justification - Both datasets are in wide format as one row represents one customer, moreover attributes are stored across multiple columns.

In [58]:
df["CustomerId"].duplicated().sum()

0

In [59]:
additional_df["CustomerId"].duplicated().sum()

9

In [60]:
df.isna().sum()

CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    0
Churn               0
dtype: int64

In [61]:
additional_df.isna().sum()

CustomerId          0
Surname             0
CreditScore         2
Geography           2
Gender              1
Age                 3
Tenure              0
Balance             3
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    1
Churn               0
dtype: int64

Structural Implications for Wrangling, Merging, and Aggregation - 

Because both datasets are structured in a wide format, data cleaning can be performed efficiently on a column-by-column basis, allowing missing values, inconsistencies, and data types to be addressed independently for each feature. This structure simplifies common preprocessing tasks such as filling in missing numerical values, standardising categorical labels, and resolving duplicate customer records. Prior to merging, precautions must be taken to ensure schema alignment, including consistent column naming and the removal or resolution of duplicate customer identifiers, as wide-format datasets rely on unique keys to avoid merge issues. Finally, the wide structure supports straightforward aggregation and analytical operations, as grouping by customer attributes and computing summary statistics can be performed directly without reshaping or pivoting the data.

Task 2

In [62]:
print("Rows in YBI dataset:", df.shape[0])

Rows in YBI dataset: 10000

In [63]:
print("Rows in additional dataset:", additional_df.shape[0])

Rows in additional dataset: 49

In [64]:
combined_df = pd.concat([df, additional_df], axis=0, ignore_index=True)

In [65]:
print("Rows after combining:", combined_df.shape[0])

Rows after combining: 10049

Approach justification - 
The two datasets were merged using vertical concatenation. This approach is suitable because both datasets outline the data of bank customers with a aligned schema, however they originate from different sources and represent different customer records. The reason for merging both datasets was to increase the sample size, and not to expand on the existing customer data. Merging by CustomerId would be inaccurate given the presence of duplicate identifiers and the lack of guaranteed correspondence between the datasets.

Data Integrity Considerations - 
Consolidation increases the amount of data that can be analyzed, but it also raises the possibility of integrity issues. These include significant gaps due to the inconsistent secondary source, duplicated customer identities, and varying data quality across datasets. Combining datasets that were gathered under various circumstances may also result in distributional bias, which has an impact on model performance and subsequent analysis. To guarantee accurate analytical results, additional validation, deduplication checks, and careful preparation are therefore necessary.

Task 3

In [66]:
print("Dataset size prior duplicate testing:", combined_df.shape)

Dataset size prior duplicate testing: (10049, 13)

In [67]:
#Exact duplicates testing
duplicates = combined_df.duplicated()
print("Number of duplicated rows:", duplicates.sum())

Number of duplicated rows: 2

In [68]:
#Key-based duplicates testing
id_duplicates = combined_df.duplicated(subset=["CustomerId"]).sum()
print("Number of duplicated CustomerId:", id_duplicates)

Number of duplicated CustomerId: 11

Type of duplicates identified

Exact duplicates - This line of code tests the exact row duplicates within the dataset where all column values are identical. More likely to occur during wide concatenation.

Key-based duplicates - This line of code tests key-based duplicates whereby the same CustomerId appears multiple times however with different attributes caused by data entry inconsistencies and data collection discrepancies.

In [69]:
combined_df = combined_df.drop_duplicates()

In [70]:
combined_df = combined_df.drop_duplicates(subset=["CustomerId"], keep="first")

Handling duplicates

Exact duplicates - This involves removing the exact duplicate leaving one copy, because exact duplicates do not provide new insights however they inflate the dataset size, potentially biasing statistical analysis and model training.

Handling Key-based duplicates - Keep the first valid occurence per CustomerId, this aids to avoid preserve maximum insights while enforcing uniqueness. Since the objective is customer based churn analysis, each customer should appear once in the dataset. Treating duplicated IDs as separate customers would violate entity integrity and distort downstream aggregation and modeling.

In [71]:
print("Dataset size after duplicate testing:", combined_df.shape)

Dataset size after duplicate testing: (10038, 13)

Approach justification - 

Duplicate analysis of the consolidated dataset identified two forms of duplication: exact row‑level duplicates and customer‑level duplication based on repeated CustomerId values. Exact duplication was detected where all attribute values were identical, while CustomerId‑based duplication reflected multiple records representing the same underlying customer entity. Quantification revealed two exact duplicates and eleven records with duplicated CustomerId values; the latter count includes the exact duplicates, as identical rows necessarily share the same identifier. Given that the analysis is conducted at the customer level, retaining multiple records per customer would bias aggregation and modelling. Accordingly, exact duplicates were removed first, followed by enforcement of CustomerId uniqueness. This reduced the dataset from 10,049 to 10,038 rows, confirming successful duplicate resolution and preservation of one‑to‑one correspondence between customers and records.

Task 4

In [72]:
#Identifies which variable contains missing values and the count of missing entries per column
combined_df.isna().sum()

CustomerId          0
Surname             0
CreditScore         1
Geography           0
Gender              1
Age                 3
Tenure              0
Balance             3
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    1
Churn               0
dtype: int64

In [73]:
#Clear quantification of missing values
missing_values = combined_df.isna().sum()
missing_percent = (missing_values / len(combined_df)) *100

missing_summary = pd.DataFrame({"Missing Values": missing_values, "Missing Percentage (%)": missing_percent})

missing_summary[missing_summary["Missing Values"] > 0]

                  Missing Values  Missing Percentage (%)
CreditScore                    1                0.009962
Gender                         1                0.009962
Age                            3                0.029886
Balance                        3                0.029886
Estimated Salary               1                0.009962

Impact of missing data - 

Missing values were identified mostly in numerical values such as Age, CreditScore, Balance and EstimatedSalary, moreover in categorical values such as Gender. Numerical values are important because they have a direct impact on churn behavior and will be utilized in aggregation and predictive modeling, these factors are significant analytically. Untreated missing values can result in incomplete feature vectors, skewed statistical summaries, and a smaller sample size through row deletion. If left untreated, missing values in the Gender variable could reduce the reliability of subsequent analysis by excluding affected records from modelling or aggregation processes. Additionally, missing gender information can distort group‑based summaries or churn comparisons by gender.

In [74]:
#Filling numerical values using median
numerical_columns = combined_df.select_dtypes(include=["int64", "float64"]).columns

for col in numerical_columns:
    if combined_df[col].isna().sum() > 0:
        combined_df[col] = combined_df[col].fillna(combined_df[col].median())

In [75]:
#Filling categorical values with mode
if combined_df["Gender"].isna().sum() > 0:
    combined_df["Gender"] = combined_df["Gender"].fillna(combined_df["Gender"].mode()[0])

In [76]:
#Confirming that all missing values have been treated
combined_df.isna().sum()

CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
Num Of Products     0
Has Credit Card     0
Is Active Member    0
Estimated Salary    0
Churn               0
dtype: int64

Justification of treating strategies

Missing values were detected and quantified across multiple numerical variables. Given their relevance to the end subsequent analysis, a median-based imputation strategy was applied to preserve dataset size and prevent bias. Moreover since Gender is a categorical variable, the missing value was therefore treated using mode imputation, which replaces the missing entry with the most frequently occuring category. This is suitable because the dominant class distribution, avoids unnecessary row deletion. After treatment it was confirmed that the dataset contains no remaining missing values, ensuring readiness for aggregation and modelling.

Task 5

In [77]:
print("Data types before refinement:")
print(combined_df.dtypes)

Data types before refinement:
CustomerId            int64
Surname              object
CreditScore         float64
Geography            object
Gender               object
Age                 float64
Tenure                int64
Balance             float64
Num Of Products       int64
Has Credit Card       int64
Is Active Member      int64
Estimated Salary    float64
Churn                 int64
dtype: object

In [78]:
#Converting Gender to categorical
combined_df["Gender"] = combined_df["Gender"].astype("category")

#Converting Geography to categorical
combined_df["Geography"] = combined_df["Geography"].astype("category")

#Converting CreditScore to integer
combined_df["CreditScore"] = combined_df["CreditScore"].astype("int64")

#Converting Age to integer
combined_df["Age"] = combined_df["Age"].astype("int64")

In [79]:
#Removing less significant nominal attributes
combined_df = combined_df.drop(columns=["Surname"])

In [80]:
print("\nData types after refinement:")
print(combined_df.dtypes)

Data types after refinement:
CustomerId             int64
CreditScore            int64
Geography           category
Gender              category
Age                    int64
Tenure                 int64
Balance              float64
Num Of Products        int64
Has Credit Card        int64
Is Active Member       int64
Estimated Salary     float64
Churn                  int64
dtype: object

In [81]:
print("\nFinal dataset shape:")
print(combined_df.shape)

Final dataset shape:
(10038, 12)

Justification -

Variables such as Gender and Geography were explicitly converted to categorical data types to reflect thier nominal nature to support efficient encoding in the following modelling steps. Moreover, variables such as CreditScore and Age were converted to integers to preserve data validation and consistency ensuring that the dataset is clean. Also, Churn was retained as an integer to preserve its binary interpretation. The less significant analytical variable, Surname, was removed as it does not contribute predictive or explanatory value which might introduce noise to the subsequent analysis.

Task 6

6.1 Customer Segmentation (Age-Based)

In [82]:
age_bins = [18, 30, 45, 60, combined_df["Age"].max() + 1]
age_labels = ["18-29", "30-44", "45-59", "60+"]

#Add age segment variable
combined_df["AgeSegment"] = pd.cut(
    combined_df["Age"],
    bins=age_bins,
    labels=age_labels,
    right=False
)

combined_df["AgeSegment"].value_counts()

AgeSegment
30-44    6032
45-59    1821
18-29    1644
60+       541
Name: count, dtype: int64

Justification of Age Segmentation

The Age variable was transformed from a continuous numerical feature into a categorical segmentation variable (AgeSegment) using predefined interval bins. This allows for group based analysis while preserving underlysing age information. This structure supports increased interpretability of anlytical results and comparison of churn pattern across age groups.

6.2 Value-Based Segmentation

In [83]:
#Threshold for high-value customers (75th percentile)
high_value_threshold = combined_df["Balance"].quantile(0.75)

#Add value-based customer segment
combined_df["ValueSegment"] = pd.cut(
    combined_df["Balance"],
    bins=[-1, 0, high_value_threshold, combined_df["Balance"].max()],
    labels=["Low Value", "Medium Value", "High Value"]
)


combined_df["ValueSegment"].value_counts()

ValueSegment
Medium Value    3910
Low Value       3618
High Value      2510
Name: count, dtype: int64

Justification of Value-Based Segmentation

For the customer value the Balance variable was used, which was then transformed into ordinal categorical variable (ValueSegment). Due to thier low financial engagement , customers with zero balances were specifically categorised as Low Value. High Value clients with above average balances were identified by segmenting the remaining customers using a quantile-based threshold; all other customers were classified as Medium Value. In order to facilitate straightforward comparison, aggregation, and analysis of customer behavior across value tiers, this transformation generates exhaustive and mutually exclusive groups.

Task 7

In [84]:
#Identifes how customer value differs across age groups
avg_balance_by_age = (
    combined_df
    .groupby("AgeSegment")["Balance"]
    .mean().reset_index(name="Average Balance")
)

avg_balance_by_age

  AgeSegment  Average Balance
0      18-29     73805.386423
1      30-44     75940.840504
2      45-59     81764.070170
3        60+     75967.858189

In [87]:
#Evaluates whether Credit Score differs between churned and retained customers
mean_credit_by_churn = (
    combined_df
    .groupby("Churn")["CreditScore"].
    mean().reset_index(name="Mean Credit Score")
)

mean_credit_by_churn

   Churn  Mean Credit Score
0      0         651.622322
1      1         644.548905

In [41]:
#Compares churn behaviour across geographic regions while outline gender per region
churn_rate_geo_gender = (
    combined_df.groupby(["Geography", "Gender"])["Churn"]
    .agg(
        Churn_Rate="mean",
        Customer_Count="count"
    )
    .reset_index()
)

churn_rate_geo_gender

  Geography  Gender  Churn_Rate  Customer_Count
0    France  Female    0.203622            2264
1    France    Male    0.127721            2756
2   Germany  Female    0.376872            1202
3   Germany    Male    0.279489            1331
4     Spain  Female    0.212980            1094
5     Spain    Male    0.132279            1391

In [42]:
#Outlines the number of customers by value
customer_count_by_value = (
    combined_df
    .groupby("ValueSegment")
    .size()
    .reset_index(name="Customer_Count")
)

customer_count_by_value

   ValueSegment  Customer_Count
0     Low Value            3618
1  Medium Value            3910
2    High Value            2510

In [43]:
#Outlines how balance differs across customer age and value tiers
avg_balance_age_value = (
    combined_df
    .groupby(["AgeSegment", "ValueSegment"])["Balance"]
    .mean()
    .reset_index(name="Average Balance")
)

avg_balance_age_value

   AgeSegment  ValueSegment  Average Balance
0       18-29     Low Value         0.000000
1       18-29  Medium Value    100540.394755
2       18-29    High Value    151016.297512
3       30-44     Low Value         0.000000
4       30-44  Medium Value    100814.154151
5       30-44    High Value    148961.004844
6       45-59     Low Value         0.000000
7       45-59  Medium Value    101875.544578
8       45-59    High Value    149515.541944
9         60+     Low Value         0.000000
10        60+  Medium Value     98649.910230
11        60+    High Value    149178.642121

Task 8

In [44]:
churn_pivot = pd.pivot_table(
    combined_df,
    values="Churn",
    index="Geography",
    columns="Gender",
    aggfunc="mean"
)

churn_pivot

Gender       Female      Male
Geography
France     0.203622  0.127721
Germany    0.376872  0.279489
Spain      0.212980  0.132279

The pivot table shows how customer churn varies by gender and geographic area. Regional disparities in turnover rates suggest that geographic considerations affect client retention, possibly due to variations in market conditions, product compatibility, or customer expectations. Further evidence that customer behavior and involvement may differ across demographic groupings comes from gender-based disparities within the same geographic area. These findings point to opportunities for focused retention tactics, where gender- and region-specific treatments could be created to lower attrition and raise customer satisfaction.